# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.11
#
# <auto-generated>
#
# Generated from file `Printer.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module Demo
_M_Demo = Ice.openModule('Demo')
__name__ = 'Demo'

if '_t_StringSeq' not in _M_Demo.__dict__:
    _M_Demo._t_StringSeq = IcePy.defineSequence('::Demo::StringSeq', (), IcePy._t_string)

_M_Demo._t_Printer = IcePy.defineValue('::Demo::Printer', Ice.Value, -1, (), False, True, None, ())

if 'PrinterPrx' not in _M_Demo.__dict__:
    _M_Demo.PrinterPrx = Ice.createTempClass()
    class PrinterPrx(Ice.ObjectPrx):

        def printString(self, s, context=None):
            return _M_Demo.Printer._op_printString.invoke(self, ((s, ), context))

        def printStringAsync(self, s, context=None):
            return _M_Demo.Printer._op_printString.invokeAsync(self, ((s, ), context))

        def begin_printString(self, s, _response=None, _ex=None, _sent=None, context=None):
            return _M_Demo.Printer._op_printString.begin(self, ((s, ), _response, _ex, _sent, context))

        def end_printString(self, _r):
            return _M_Demo.Printer._op_printString.end(self, _r)

        def toUpper(self, s, context=None):
            return _M_Demo.Printer._op_toUpper.invoke(self, ((s, ), context))

        def toUpperAsync(self, s, context=None):
            return _M_Demo.Printer._op_toUpper.invokeAsync(self, ((s, ), context))

        def begin_toUpper(self, s, _response=None, _ex=None, _sent=None, context=None):
            return _M_Demo.Printer._op_toUpper.begin(self, ((s, ), _response, _ex, _sent, context))

        def end_toUpper(self, _r):
            return _M_Demo.Printer._op_toUpper.end(self, _r)

        def countWords(self, s, context=None):
            return _M_Demo.Printer._op_countWords.invoke(self, ((s, ), context))

        def countWordsAsync(self, s, context=None):
            return _M_Demo.Printer._op_countWords.invokeAsync(self, ((s, ), context))

        def begin_countWords(self, s, _response=None, _ex=None, _sent=None, context=None):
            return _M_Demo.Printer._op_countWords.begin(self, ((s, ), _response, _ex, _sent, context))

        def end_countWords(self, _r):
            return _M_Demo.Printer._op_countWords.end(self, _r)

        def getHistory(self, context=None):
            return _M_Demo.Printer._op_getHistory.invoke(self, ((), context))

        def getHistoryAsync(self, context=None):
            return _M_Demo.Printer._op_getHistory.invokeAsync(self, ((), context))

        def begin_getHistory(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_Demo.Printer._op_getHistory.begin(self, ((), _response, _ex, _sent, context))

        def end_getHistory(self, _r):
            return _M_Demo.Printer._op_getHistory.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_Demo.PrinterPrx.ice_checkedCast(proxy, '::Demo::Printer', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_Demo.PrinterPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::Demo::Printer'
    _M_Demo._t_PrinterPrx = IcePy.defineProxy('::Demo::Printer', PrinterPrx)

    _M_Demo.PrinterPrx = PrinterPrx
    del PrinterPrx

    _M_Demo.Printer = Ice.createTempClass()
    class Printer(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Demo::Printer', '::Ice::Object')

        def ice_id(self, current=None):
            return '::Demo::Printer'

        @staticmethod
        def ice_staticId():
            return '::Demo::Printer'

        def printString(self, s, current=None):
            raise NotImplementedError("servant method 'printString' not implemented")

        def toUpper(self, s, current=None):
            raise NotImplementedError("servant method 'toUpper' not implemented")

        def countWords(self, s, current=None):
            raise NotImplementedError("servant method 'countWords' not implemented")

        def getHistory(self, current=None):
            raise NotImplementedError("servant method 'getHistory' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_Demo._t_PrinterDisp)

        __repr__ = __str__

    _M_Demo._t_PrinterDisp = IcePy.defineClass('::Demo::Printer', Printer, (), None, ())
    Printer._ice_type = _M_Demo._t_PrinterDisp

    Printer._op_printString = IcePy.Operation('printString', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), ((), IcePy._t_string, False, 0), ())
    Printer._op_toUpper = IcePy.Operation('toUpper', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), ((), IcePy._t_string, False, 0), ())
    Printer._op_countWords = IcePy.Operation('countWords', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), ((), IcePy._t_int, False, 0), ())
    Printer._op_getHistory = IcePy.Operation('getHistory', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), _M_Demo._t_StringSeq, False, 0), ())

    _M_Demo.Printer = Printer
    del Printer

# End of module Demo
